# Imginer   core        in-picture     out-picture  flag out-fontsfile    Ascii
# 26big
./Imager.exe 1 ../doc/fonts/26big/A.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 65 
./Imager.exe 1 ../doc/fonts/26big/B.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 66
./Imager.exe 1 ../doc/fonts/26big/C.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 67
./Imager.exe 1 ../doc/fonts/26big/D.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 68
./Imager.exe 1 ../doc/fonts/26big/E.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 69
./Imager.exe 1 ../doc/fonts/26big/F.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 70
./Imager.exe 1 ../doc/fonts/26big/G.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 71
./Imager.exe 1 ../doc/fonts/26big/H.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 72
./Imager.exe 1 ../doc/fonts/26big/I.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 73
./Imager.exe 1 ../doc/fonts/26big/J.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 74
./Imager.exe 1 ../doc/fonts/26big/K.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 75
./Imager.exe 1 ../doc/fonts/26big/L.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 76
./Imager.exe 1 ../doc/fonts/26big/M.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 77
./Imager.exe 1 ../doc/fonts/26big/N.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 78
./Imager.exe 1 ../doc/fonts/26big/O.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 79
./Imager.exe 1 ../doc/fonts/26big/P.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 80
./Imager.exe 1 ../doc/fonts/26big/Q.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 81
./Imager.exe 1 ../doc/fonts/26big/R.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 82
./Imager.exe 1 ../doc/fonts/26big/S.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 83
./Imager.exe 1 ../doc/fonts/26big/T.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 84
./Imager.exe 1 ../doc/fonts/26big/U.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 85
./Imager.exe 1 ../doc/fonts/26big/V.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 86
./Imager.exe 1 ../doc/fonts/26big/W.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 87
./Imager.exe 1 ../doc/fonts/26big/X.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 88
./Imager.exe 1 ../doc/fonts/26big/Y.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 89
./Imager.exe 1 ../doc/fonts/26big/Z.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 90
# number
./Imager.exe 1 ../doc/fonts/number/0.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 48 
./Imager.exe 1 ../doc/fonts/number/1.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 49
./Imager.exe 1 ../doc/fonts/number/2.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 50
./Imager.exe 1 ../doc/fonts/number/3.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 51
./Imager.exe 1 ../doc/fonts/number/4.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 52
./Imager.exe 1 ../doc/fonts/number/5.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 53
./Imager.exe 1 ../doc/fonts/number/6.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 54
./Imager.exe 1 ../doc/fonts/number/7.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 55
./Imager.exe 1 ../doc/fonts/number/8.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 56
./Imager.exe 1 ../doc/fonts/number/9.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 57
# 26small
./Imager.exe 1 ../doc/fonts/26small/a.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 97 
./Imager.exe 1 ../doc/fonts/26small/b.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 98
./Imager.exe 1 ../doc/fonts/26small/c.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 99
./Imager.exe 1 ../doc/fonts/26small/d.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 100
./Imager.exe 1 ../doc/fonts/26small/e.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 101
./Imager.exe 1 ../doc/fonts/26small/f.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 102
./Imager.exe 1 ../doc/fonts/26small/G.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 103
./Imager.exe 1 ../doc/fonts/26small/h.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 104
./Imager.exe 1 ../doc/fonts/26small/i.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 105
./Imager.exe 1 ../doc/fonts/26small/j.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 106
./Imager.exe 1 ../doc/fonts/26small/k.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 107
./Imager.exe 1 ../doc/fonts/26small/l.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 108
./Imager.exe 1 ../doc/fonts/26small/m.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 109
./Imager.exe 1 ../doc/fonts/26small/n.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 110
./Imager.exe 1 ../doc/fonts/26small/o.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 111
./Imager.exe 1 ../doc/fonts/26small/p.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 112
./Imager.exe 1 ../doc/fonts/26small/q.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 113
./Imager.exe 1 ../doc/fonts/26small/r.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 114
./Imager.exe 1 ../doc/fonts/26small/s.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 115
./Imager.exe 1 ../doc/fonts/26small/t.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 116
./Imager.exe 1 ../doc/fonts/26small/u.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 117
./Imager.exe 1 ../doc/fonts/26small/v.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 118
./Imager.exe 1 ../doc/fonts/26small/w.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 119
./Imager.exe 1 ../doc/fonts/26small/x.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 120
./Imager.exe 1 ../doc/fonts/26small/y.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 121
./Imager.exe 1 ../doc/fonts/26small/z.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 122
# symbol
./Imager.exe 1 ../doc/fonts/symbol/00.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 126 
./Imager.exe 1 ../doc/fonts/symbol/01.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 96
./Imager.exe 1 ../doc/fonts/symbol/02.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 33
./Imager.exe 1 ../doc/fonts/symbol/03.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 64
./Imager.exe 1 ../doc/fonts/symbol/04.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 35
./Imager.exe 1 ../doc/fonts/symbol/05.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 36
./Imager.exe 1 ../doc/fonts/symbol/06.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 37
./Imager.exe 1 ../doc/fonts/symbol/07.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 94
./Imager.exe 1 ../doc/fonts/symbol/08.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 38
./Imager.exe 1 ../doc/fonts/symbol/09.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 42
./Imager.exe 1 ../doc/fonts/symbol/10.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 40
./Imager.exe 1 ../doc/fonts/symbol/11.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 41
./Imager.exe 1 ../doc/fonts/symbol/12.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 95
./Imager.exe 1 ../doc/fonts/symbol/13.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 45
./Imager.exe 1 ../doc/fonts/symbol/14.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 43
./Imager.exe 1 ../doc/fonts/symbol/15.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 61
./Imager.exe 1 ../doc/fonts/symbol/16.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 47
./Imager.exe 1 ../doc/fonts/symbol/17.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 123
./Imager.exe 1 ../doc/fonts/symbol/18.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 124
./Imager.exe 1 ../doc/fonts/symbol/19.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 91
./Imager.exe 1 ../doc/fonts/symbol/20.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 93
./Imager.exe 1 ../doc/fonts/symbol/21.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 124
./Imager.exe 1 ../doc/fonts/symbol/22.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 92
./Imager.exe 1 ../doc/fonts/symbol/23.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 58
./Imager.exe 1 ../doc/fonts/symbol/24.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 59
./Imager.exe 1 ../doc/fonts/symbol/25.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 34
./Imager.exe 1 ../doc/fonts/symbol/26.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 39
./Imager.exe 1 ../doc/fonts/symbol/27.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 60 
./Imager.exe 1 ../doc/fonts/symbol/28.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 62
./Imager.exe 1 ../doc/fonts/symbol/29.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 44
./Imager.exe 1 ../doc/fonts/symbol/30.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 46
./Imager.exe 1 ../doc/fonts/symbol/31.bmp ./tmp.bmp -E ../doc/fonts/fonts.if 63
